# Uncomment the next line to define a global platform for your project
platform :ios, '11.1'

target 'TheHerbalEscape' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TheHerbalEscape
  pod 'PureLayout'

  target 'TheHerbalEscapeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TheHerbalEscapeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
