//
//  SegueIdentifiers.swift
//  TheHerbalEscape
//
//  Created by Oliver Samson on 25/11/2017.
//  Copyright © 2017 Oliver Samson. All rights reserved.
//

import Foundation

/// Segue identifiers that need to be referenced in code.
struct SegueIdentifiers {
    /// This is a guess because I think this is autogenerated.
    static let ShowDetailIdentifier = "showDetail"
}
